"""Write the repository's standing documentation and CI definitions.

Generated by script so that the pinned versions and the finding list have one
source of truth rather than being restated in five places by hand.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

LICENSE = """MIT License

Copyright (c) 2026 The CivicDividendOS authors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

---

This licence covers the source code in src/, scripts/, tests/ and configs/.
The manuscript (CivicDividendOS_v2.tex and its PDF), its figures and its
bibliography are the authors' work and are not covered by it.

The software is research code. Its outputs are not legal, tax, financial or
investment advice.
"""

CITATION = """cff-version: 1.2.0
message: >-
  If you use this software or its results, please cite it. Author details are
  incomplete and REQUIRE AUTHOR INPUT before publication; the placeholder below
  must not be treated as an attribution.
title: "CivicDividendOS: attribution-based taxation of autonomous economic activity"
abstract: >-
  A framework and computational testbed for taxing the attributed economic
  origin of value produced by AI agents and robots, using the Shapley value of a
  factor of production as a contribution base. Includes the corrected testbed
  following the independent audit of 2026-09-06.
type: software
version: "1.0.0"
date-released: "{today}"
license: MIT
keywords:
  - automation taxation
  - Shapley value
  - public finance
  - heterogeneous agent model
  - reproducible research
authors:
  - family-names: "REQUIRES AUTHOR INPUT"
    given-names: "REQUIRES AUTHOR INPUT"
    affiliation: "REQUIRES AUTHOR INPUT"
references:
  - type: report
    title: "Independent audit of the CivicDividendOS manuscript and testbed"
    year: 2026
    notes: "audit/AUDIT_REPORT.html; the P0 findings F1-F3 are addressed in v1.0.0"
"""

CONTRIBUTING = """# Contributing

## Ground rules

This is a research repository, so the bar is scientific rather than stylistic.

1. **Never loosen a tolerance to make a test pass.** If a numerical test fails,
   find out why. The audit's F3 finding survived to publication because nothing
   ever checked whether the books closed; a test that has been relaxed until it
   is green is worse than no test.
2. **Never delete a failing test that reveals a real problem.** Mark it
   `xfail` with a reason and open an issue.
3. **Never hand-type a number into the manuscript.** All results tables are
   generated by `make tables` and pulled in with `\\input`. CI runs
   `scripts/verify_generated.py` and fails on drift.
4. **`legacy_mode` must stay bit-exact.** `tests/regression/` proves the
   corrected model reproduces `simulation/cdos_sim.py` exactly. If that breaks,
   something changed that nobody decided on.
5. **`simulation/` and `audit/` are frozen.** They are the audited baseline and
   the evidence of what the project looked like before remediation.

## Making a scientific change

Record it in `CHANGELOG.md` and `MEMORY.md` with: the problem, the original
behaviour, the new behaviour, the scientific justification, the files changed,
the tests added, the experiments affected, and the paper sections affected.

## Before opening a pull request

```bash
make lint
make test
make smoke
make tables && make verify
```

## Adding a parameter

Add it to the relevant dataclass in `src/cdos/config.py` with a comment saying
what it is and where it comes from. Never read a constant from inside a model
function — that is what made finding F1 possible.

## Adding an experiment

Add a YAML file to `experiments/`. It must carry an `experiment_id`, a
`description` saying what scientific question it answers, and the `arms` and
`seeds` it needs. An experiment that exists only to increase the count of
experiments should not be added.
"""

SECURITY = """# Security and responsible use

## Reporting

This is research software with no network surface, no authentication and no
persistent service. If you find a vulnerability in the code — for example
unsafe deserialisation in the config loader — please open a private security
advisory rather than a public issue.

## What this software is not

- It is **not** a tax filing, assessment or compliance system.
- Its outputs are **not** legal, tax, financial or investment advice.
- Simulated rates are **not** real tax rates and must not be presented as such.
- The Deployment Nexus is a research construct, not a claim about any
  jurisdiction's law.

## Data protection

The framework as specified assumes task-level metering of production episodes.
Where episodes are attributable to identifiable workers this is personal data,
and the framework does **not** include the disclosure limits such metering
would require. Anyone implementing the measurement layer against real workplace
data needs a lawful basis, a data-protection impact assessment and minimisation
controls that this repository does not provide.

## No secrets

This repository contains no credentials, keys or tokens, and none should ever
be committed. `.gitignore` excludes `.env` and local environment files.

## Licensed data

No external data is redistributed here. Several intended calibration sources
prohibit redistribution; `configs/calibration.yaml` records their status.
Do not commit licensed series into this repository.
"""

CI = """name: CI

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e . --no-deps

      - name: Record the environment
        run: |
          python -c "import sys, numpy; print(sys.version); print('numpy', numpy.__version__)"

      - name: Lint
        run: python -m ruff check src tests scripts

      - name: Unit tests
        run: python -m pytest tests/unit -q

      - name: Numerical tests
        run: python -m pytest tests/numerical -q

      - name: Integration tests
        run: python -m pytest tests/integration -q

      - name: Regression tests against the audited baseline
        run: python -m pytest tests/regression -q

      - name: Two-seed smoke campaign
        run: |
          python scripts/run_campaign.py --seeds 2 \\
            --arms B0 B1 B4 B6 B6c --out results/raw/ci_smoke.json \\
            --experiment-id ci_smoke

      - name: Validate the artefacts the smoke run produced
        run: |
          python - <<'PY'
          import json, sys
          from pathlib import Path
          agg = json.load(open("results/raw/ci_smoke.json"))
          manifest = json.load(open("results/manifests/ci_smoke.json"))
          assert manifest["git"]["sha"], "manifest recorded no git SHA"
          assert manifest["environment"]["packages"]["numpy"] == "1.26.4"
          for arm in ("B0", "B1", "B4", "B6", "B6c"):
              assert arm in agg, f"arm {arm} missing from the aggregate"
              assert agg[arm]["Y"]["mean"] > 0
          print("artefacts valid")
          PY

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-results
          path: |
            results/raw/ci_smoke*.json
            results/manifests/ci_smoke.json

  paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install
        run: |
          pip install -r requirements-dev.txt
          pip install -e . --no-deps

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \\
            texlive-latex-recommended texlive-latex-extra \\
            texlive-fonts-recommended texlive-science texlive-pictures latexmk

      - name: Check the generated tables have not drifted
        run: python scripts/verify_generated.py --allow-missing

      - name: Compile the manuscript
        run: latexmk -pdf -interaction=nonstopmode -halt-on-error CivicDividendOS_v2.tex

      - name: Upload the PDF
        uses: actions/upload-artifact@v4
        with:
          name: manuscript
          path: CivicDividendOS_v2.pdf
"""

REPRODUCTION = """name: Reproduction

# The heavy experiment matrix. Not run on every push: it takes hours.
on:
  workflow_dispatch:
    inputs:
      seeds:
        description: "seeds per arm"
        default: "20"
      pattern:
        description: "experiment glob, e.g. E0* or A*"
        default: "E*"
  schedule:
    - cron: "0 3 1 * *"

jobs:
  reproduce:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install
        run: |
          pip install -r requirements-dev.txt
          pip install -e . --no-deps

      - name: Verify the audited baseline still reproduces bit-exactly
        run: python -m pytest tests/regression -q

      - name: Headline campaign
        run: python scripts/run_campaign.py --seeds ${{ github.event.inputs.seeds || 20 }}

      - name: Experiment matrix
        run: |
          python scripts/run_all_experiments.py \\
            --pattern '${{ github.event.inputs.pattern || 'E*' }}' \\
            --seeds ${{ github.event.inputs.seeds || 20 }}

      - name: Regenerate tables and figures
        run: |
          python scripts/make_tables.py
          python scripts/make_figures.py

      - name: Report numerical drift against the committed tables
        run: python scripts/verify_generated.py --report-only

      - name: Upload everything
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reproduction
          path: |
            results/
            figures/
            tables/
            paper/generated/
"""


def main() -> None:
    (ROOT / "LICENSE").write_text(LICENSE, encoding="utf-8", newline="\n")
    (ROOT / "CITATION.cff").write_text(
        CITATION.format(today=date.today().isoformat()),
        encoding="utf-8", newline="\n")
    (ROOT / "CONTRIBUTING.md").write_text(CONTRIBUTING, encoding="utf-8", newline="\n")
    (ROOT / "SECURITY.md").write_text(SECURITY, encoding="utf-8", newline="\n")
    wf = ROOT / ".github" / "workflows"
    wf.mkdir(parents=True, exist_ok=True)
    (wf / "ci.yml").write_text(CI, encoding="utf-8", newline="\n")
    (wf / "reproduction.yml").write_text(REPRODUCTION, encoding="utf-8", newline="\n")
    print("wrote LICENSE, CITATION.cff, CONTRIBUTING.md, SECURITY.md, "
          ".github/workflows/{ci,reproduction}.yml")


if __name__ == "__main__":
    main()
