"""Fail if any generated table has drifted from the results that produced it.

The audit found the manuscript's numbers were hand-pasted. Generated artefacts
existed, they still agreed at the time of the audit, and nothing enforced it.
This is the enforcement: regenerate every table into a temporary directory and
compare, ignoring the provenance header (which legitimately changes with the
git SHA).

    python scripts/verify_generated.py                # fail on any drift
    python scripts/verify_generated.py --report-only  # report, exit 0
    python scripts/verify_generated.py --allow-missing

Exit codes: 0 clean, 1 drift detected, 2 nothing to check.
"""

from __future__ import annotations

import argparse
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

GEN = ROOT / "paper" / "generated"


def _body(text: str) -> str:
    """Strip the leading provenance comment block."""
    lines = [ln for ln in text.splitlines() if not ln.startswith("%")]
    return "\n".join(ln.rstrip() for ln in lines).strip()


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--report-only", action="store_true")
    ap.add_argument("--allow-missing", action="store_true",
                    help="exit 0 when no results are present to regenerate from")
    args = ap.parse_args(argv)

    committed = sorted(GEN.glob("*.tex"))
    if not committed:
        print("no generated tables are committed yet")
        return 0 if args.allow_missing else 2

    with tempfile.TemporaryDirectory() as tmp:
        tmp_gen = Path(tmp) / "generated"
        tmp_tables = Path(tmp) / "tables"
        import scripts.make_tables as mt  # noqa: E402
        original_gen, original_tables = mt.GEN, mt.TABLES
        mt.GEN, mt.TABLES = tmp_gen, tmp_tables
        try:
            code = mt.main()
        finally:
            mt.GEN, mt.TABLES = original_gen, original_tables

        if code != 0:
            print("could not regenerate: no results present")
            return 0 if args.allow_missing else 2

        drift: list[tuple[str, str]] = []
        checked = 0
        for path in committed:
            fresh = tmp_gen / path.name
            if not fresh.exists():
                drift.append((path.name, "no longer generated by make_tables.py"))
                continue
            checked += 1
            if _body(path.read_text(encoding="utf-8")) != \
                    _body(fresh.read_text(encoding="utf-8")):
                drift.append((path.name, "content differs from a fresh regeneration"))

    print(f"\nchecked {checked} generated table(s)")
    if not drift:
        print("no numerical drift: every committed table matches its results")
        return 0

    print("\nDRIFT DETECTED -- a table in the paper no longer matches its results:")
    for name, reason in drift:
        print(f"  {name}: {reason}")
    print("\nRun `make tables` and commit the result, or find out why the "
          "numbers moved.")
    return 0 if args.report_only else 1


if __name__ == "__main__":
    sys.path.insert(0, str(ROOT))
    raise SystemExit(main())
